# CCD2 preprocessing pipeline
steps:
    - class_name: src.data.preprocessing.CutNoise
      init_args:
          noise_level: 0.5e-6
          both_directions: false
    - class_name: src.data.preprocessing.LogTransform
      init_args:
          eps: 1.0e-08
    - class_name: src.data.preprocessing.Standarize
      init_args:
          mean: -15.7554139
          std: 4.7630354
