# CCD2 preprocessing aligned to diffusion4sim/configs/train/ccd2.yaml.
steps:
  - class_name: src.data.preprocessing.CutNoise
    init_args:
      noise_level: 1.65e-07
      both_directions: true
  - class_name: src.data.preprocessing.LogTransform
    init_args:
      eps: 1.0e-06
  - class_name: src.data.preprocessing.Standarize
    init_args:
      mean: -12.275526
      std: 2.8429077
