# CCD3 preprocessing pipeline for energy-only conditioning
# raw cut -> x / 10 -> log -> standardize
steps:
  - class_name: src.data.preprocessing.CutNoise
    init_args:
      noise_level: 5.0e-07
      both_directions: true
  - class_name: src.data.preprocessing.ScaleByFactor
    init_args:
      factor: 10
  - class_name: src.data.preprocessing.LogTransform
    init_args:
      eps: 1.0e-06
  - class_name: src.data.preprocessing.Standarize
    init_args:
      mean: -13.4442820
      std: 1.1747618
