target: src.models.CaloDiTPaper
init_args:
  input_size: [9, 16, 45]
  patch_size: [3, 2, 3]
  conditions_size: [1, 2, 1]
  in_channels: 1
  out_channels: 1
  emb_dim: 264
  num_heads: 4
  num_layers: 6
  mlp_ratio: 4
