kind: flow
target: src.flow.FlowMatching
init_args:
  predict_mode: pred_x1
  loss_target: v
  time_sampler: logit_normal
  logit_normal_mean: 0.0
  logit_normal_std: 1.0
  noise_scale: 1.0
  t_eps: 1.0e-3
