kind: flow
target: src.flow.FlowMatching
init_args:
  predict_mode: pred_x1
  loss_target: v
  time_sampler: logit_normal
  logit_normal_mean: -0.8
  logit_normal_std: 0.8
  noise_scale: 1.0
  t_eps: 5.0e-2
  time_behavior: original
